// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoeShop.Models;

public partial class ShoeImage
{
    public int ImageId { get; set; }

    public int ShoeId { get; set; }

    public string ImageUrl { get; set; }

    public bool IsMain { get; set; }

    public virtual Shoe Shoe { get; set; }
}